### ISSUE TITLE
Importing OEM data message with long trajectory crashes due to unbounded memory usage of Regex

### ISSUE THREAD

**Issue by noc0lour** [bradsease/oem#35]
**Describe the bug**
When importing an OEM file in KVN format with a size of 450 MB which contains about 7 years of trajectory data the regex match statement in `_from_kvm_oem()` immediately hogs > 16GB RAM and gets killed. Maybe a transition to a slower, but more stable state machine processing line by line as in https://gitlab.com/jorispio/ccsds2czml. Although the parsing algorithm there is also behaving poorly with multiple segments.

I've tried to use google/re2 python wrappers for a more efficient processing of the file, but still fails.
I'll take a look on rewriting the parser.

Edit: only the `match()` call seems to create issues, `find_all()` and running the match for the header section separately works fine.

**Comment by bradsease** [comment]
Hi @noc0lour, thanks for reporting this issue. I think I potentially have a fix for this (see the linked pull request). I'm going to try to reproduce the error on my end with some test cases, but could you also check to see if the changes address your problem?

**Comment by noc0lour** [comment]
I just tried from `master` branch and it works like a charm, I still need ~8GB of RAM to read everything in, but that's fine for reading almost 10 years of trajectory in.
