### ISSUE TITLE
Metadata.py: please check if required standard keyword string typo "USEABLE..." -> "USABLE..."

### ISSUE THREAD

**Issue by frankweischede** [bradsease/oem#76]
**Describe the bug**
Using an existing OEM file the string (header key) "USABLE_START_TIME" was found to be invalid: an error on that string was raised. Apparently all corresponding keys found in the metadata.py module to contain a typo ("USEABLE_...") need to be corrected to "USABLE_..."; a performed test (changing key in metadata.py) was resulting in the code to successfully accept the corrected key.

**Steps to Reproduce**
- introduce test header items "USABLE_START_TIME" (and USABLE_STOP_TIME) plus a suited/valid value into any OEM sample file; 
- check for error messaging;

```python
# Insert reproducing code snippet here

#
# not needed, please see description of the proposed reproduction steps
#

**Python/Package Version Information**
Python: v3.9.5
oem: v0.3.3

**Comment by bradsease** [comment]
Hello & thank you for your input! It didn't cross my mind that there might be two spellings -- a quick search says they are both technically valid regional variations. The OEM specification (https://public.ccsds.org/Pubs/502x0b2c1e2.pdf) dictates the spelling should be "USEABLE" and doesn't mention any alternatives so I'm inclined to keep it unchanged.

I'm curious about the source of the OEM that caused this error. Is it hand-made or from another software package?

**Comment by frankweischede** [comment]
Hello Brad,


My name is Frank Weischede and I am working as a spaceflight dynamics consultant. 

My customer recently provided me an example OEM that contained the keys

USABLE_START_TIME and
USABLE_STOP_TIME

I wrote a simple reader for it using Fortran and also tried to read with your python oem reader. 

Obviously the error was inevitably due to the different spellings that have been setup in general.

When I checked with my usual German/English online dictionary it only offers „usable“. 

Unfortunately, I believed the dictionary to be correct (although I thought that I had seen „useable“ before) and I did not look up how the CCSDS blue book defined the keywords.

Now, obviously, you are fully right and the two valid spellings exist, although there might be indications that „useable“ is the by far less used one in the world (again, an interpretation just made from a single quick-search result).

As a summary, the spelling you use is correct and also defined by CCSDS for the OEM meta data section. 

By contrast, my OEM sample is erroneous in terms of the definition made by CCSDS.

All this suggests that the bug report I initiated needs to be retracted/withdrawn. My OEM source is the one to be corrected instead.

So apologies for the trouble (benefit for me: I know have a Github account ;) and I will report this issue to my customer and it will be indeed interesting for what reason an official spaceflight product using the standard could have been incorrectly setup.

I am happy to keep you posted on what the reason was.


Best regards,

Frank

**Comment by frankweischede** [comment]
After short discussion and inspection it is obvious that the observed issue with different spellings of the word "useable"/"usable" is not originating from the oem tool as it correctly implements what is reported in the CCSDS OEM standard for meta data keywords. If different spelling might be a relevant issue in standardization, needs to be discussed at a different place. However, here I see the root cause, that can lead to a standard implementation error, is that different (kinds of valid) spelling has the general potential that it can be overlooked or mixed-up by everybody.

Apologies, Brad, for this "incident", and thanks for your tool being available!

Frank
