### ISSUE TITLE
Missing line_number in err method call

### ISSUE THREAD

**Issue by josephgruber** [bradsease/oem#80]
**Describe the bug**
In the `parse_kvn_oem` method, if the CCSDS_OEM_VERS keyword is missing as the first line, the `err` method is called but is missing the `line_number` parameter value. This results in a TypeError being thrown.

https://github.com/bradsease/oem/blob/main/oem/parsers.py#L53

PR for fix: https://github.com/bradsease/oem/pull/81

**Steps to Reproduce**
Provide any OEM file that does not have the `CCSDS_OEM_VERS` keyword as the first line

**Python/Package Version Information**
Python: [e.g. 3.5.1] 3.11.6
oem: [e.g. 1.0.0] 0.4.0

**Comment by bradsease** [comment]
Thanks for the fix, @josephgruber!
